services:
  backend:
    image: ghcr.io/yassinesahli04/environmentalstationsdata-backend:${BACKEND_TAG:-latest}
    pull_policy: always
    restart: unless-stopped
    ports:
      - "8001:8000"
    volumes:
      - ./Secrets/DbInfo.json:/run/secrets/DbInfo.json:ro
      - ./Secrets/C2aiInfo.json:/run/secrets/C2aiInfo.json:ro
      - ./Secrets/clerk_secret_key:/run/secrets/clerk_secret_key:ro
    environment:
      - CLERK_KEY_PATH=/run/secrets/clerk_secret_key
      - DBINFO_PATH=/run/secrets/DbInfo.json
      - C2AIINFO_PATH=/run/secrets/C2aiInfo.json
      - REDIS_URL=redis://redis:6379/0
      - WATCHFILES_FORCE_POLLING=true
      - AGENT_URL=http://ai-agent:8001

  redis:
    image: redis:8.2-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  worker:
    image: ghcr.io/yassinesahli04/environmentalstationsdata-worker:${WORKER_TAG:-latest}
    pull_policy: always
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - ./Secrets/DbInfo.json:/run/secrets/DbInfo.json:ro
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DBINFO_PATH=/run/secrets/DbInfo.json

  scheduler:
    image: ghcr.io/yassinesahli04/environmentalstationsdata-scheduler:${SCHEDULER_TAG:-latest}
    pull_policy: always
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - UPDATE_URL=http://backend:8000/api/stations/server/update-db
      - PYTHONUNBUFFERED=1

  mcp-server-chart:
    image: docker.io/acuvity/mcp-server-chart:0.9.7
    ports:
      - "8000:8000"
    read_only: true

  ai-agent:
    image: ghcr.io/yassinesahli04/environmentalstationsdata-agent:${AGENT_TAG:-latest}
    pull_policy: always
    restart: unless-stopped
    depends_on:
      - mcp-server-chart
      - backend
    ports:
      - "8001"
    volumes:
      - ./AiAgent/output:/app/AiAgent/output
      - ./Secrets/openAi_key:/run/secrets/openAi_key:ro
      - ./Secrets/langfuse_pk:/run/secrets/angfuse_pk:ro
      - ./Secrets/langfuse_sk:/run/secrets/angfuse_sk:ro
    environment:
      - OPENAI_KEY_PATH=/run/secrets/openAi_key
      - USE_OPENAI=true
      - BACKEND_URL=http://backend:8000
      - EXPORT_DIR=/app/AiAgent/output
