services:
  backend-dev:
    build:
      context: ./BackEnd
      dockerfile: Dockerfile.dev
    ports:
      - 8888:8888
      - 5678:5678
    volumes:
      - ./PlaygroundFile.ipynb:/app/PlaygroundFile.ipynb
      - ./BackEnd:/app/BackEnd
      - ./Secrets/DbInfo.json:/run/secrets/DbInfo.json:ro
      - ./Secrets/C2aiInfo.json:/run/secrets/C2aiInfo.json:ro
    environment:
      - DBINFO_PATH=/run/secrets/DbInfo.json
      - C2AIINFO_PATH=/run/secrets/C2aiInfo.json
      - REDIS_URL=redis://redis:6379/0
